# Site settings
title: "MxeraL"
description: > 
  I'm learning machine.

author: Xera
email: leexera@github.com
instagram_username: x_eraa_
github_username: leexera

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leexera.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

